### ISSUE TITLE
Publish to IPFS? :D

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/arewedistributedyet#2]
Pretty please! :D

**Comment by VictorBjelkholm** [comment]
First step was done: https://github.com/ipfs-shipyard/arewedistributedyet/pull/1

Second step is I have to fix this: https://github.com/ipfs/jenkins-libs/issues/5

Third is that I need @lgierth to tell me where the DNS record is at. It's not at dnsimple AFAIK.

**Comment by VictorBjelkholm** [comment]
DONE! http://arewedistributedyet.com/
